---
- hosts: all 

  tasks: 

  - include_vars: ../vars/list_soft.yml

  - name: add ppa repo
    become: yes
    apt_repository:
      repo: "{{ item.ppa_repo }}"
    with_items: "{{ list_ppa }}"

  # - name: update
  #  become: yes
  #  apt:
  #    update-cache: yes
  #    state: latest

    #установка из репозиториев Ubuntu
  - name: install 
    become: yes
    apt: 
      name: "{{ item.name }}" 
      state: "{{ item.state }}"
      update_cache: "{{ item.update_cache }}"
    with_items: "{{list_soft}}"

    #скачивание deb пакетов       
  - name: download deb
    become: yes
    get_url:
      url: "{{ item.url }}"
      dest: /home/{{ item.user_name }}/Downloads/{{ item.name }}
    with_items: "{{ list_url }}"

    #установка из deb пакетов
  - name: install from deb
    become: yes
    apt: 
      deb: /home/{{item.user_name}}/Downloads/{{item.name}}
    with_items: "{{list_url}}"
